# -*- coding: utf-8 -*-
"""Copy of ocpd

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EQ7JMC2A2fWbbG64TJ8eR5aVGqKdilc_
"""

#exercise 1:
#has_homework = True
#has_free_time = False

#x= 'True'
#y= 'False'
#today = "has_homework"

#if today == "has_homework":
  #print(y)
#else:
    #print(x)

#exercise 2:
#my_pets = ['dog', 'cat', 'fish', 'bird']
#my_pets[2:2] = ["hamster", "squirrel"]
#my_pets.remove('dog')
#my_pets[0,1,2,3,4]
#my_pets[0], my_pets[2] = my_pets[2], my_pets[0]
#print(my_pets)
#my_favorite_pets = ['dog','hamster']
#print(my_favorite_pets)
##phrase = "Python programming is fun!"
#count_i = phrase.count('i')
#print("Number of occurrences of 'i':", count_i)
#new_phrase = phrase.replace("Python", "computer")
#print(new_phrase)

#exercise 4:
#my_numbers = (1, 2, 3, 4, 5, 6)
# Print and try to modify the tuple
##print(my_numbers[0])
#print(my_numbers[5])
#new_value = 8
#new_numbers = tuple(new_value if x == 3 else x for x in my_numbers)
#print(new_numbers)


#exercise 5:
#student_info = {"name": "Alex", "grade_level": 10, "favorite_subject": "ELA","personal_hobbies":"badminton" "table_tennis" "swimming"}
# Modify the dictionary as instructed
#print(student_info['name'])
#print(student_info["grade_level"])
#print(student_info["favorite_subject"])
#print(student_info["personal_hobbies"])

#exercise 6:
#day = "Saturday"
#weather = "Sunny"
##Saturaday_weather = "Sunny"
#Sunday_weather = "rainy"
# Write the conditional statements
#if Saturaday_weather == "Sunny":
  ##print("lets_go_hike!")
#elif Sunday_weather == "rainy":
  #print("stay_at_home.")
#else:
  #print("lets_go_hike!")

  # Exercise 1
#likes_math = True
#has_math_homework = True
#has_calculator = False

#me = 'likes_math'
#hw = 'has_math_homework'
#tool = 'has_calculator'

#if me == 'likes_math' and hw == 'has_math_homework' and tool == 'has_calculator':
  #print('ready to do math homwork.')
#elif me == "dont likes math":
  #print('not ready to do math homwork')
#else:
  #print('ready to do math homework')


# Exercise 2
#numbers = [3, 1, 4, 1, 5, 9, 2, 6]
#names = ['Alice', 'Bob', 'Charlie']

#sorted_numbers = sorted(numbers)

#print(sorted_numbers)

#combined_list = numbers + names
#print(combined_list)

#combined_list = [1, 2, 3, 'Alice', 'Bob', 'Charlie']

#new_num = combined_list[:3]
#new_name = combined_list[3:]

#print("new_num:", new_num)
#print("new_name:", new_name)


# Exercise 3
sentence = "Learning Python programming is exciting!"
#phrase = "Learning Python programming is exciting!"
#count_Python = phrase.count('Python')
#print("Number of occurrences of 'Python':", count_Python)
#sentence = "Learning Python programming is exciting!"
#capitalized_sentence = sentence.title()
#print(capitalized_sentence)


# Exercise 4
my_mixed_tuple =  (4, 'banana', [1, 2, 3], 7.5)
#print(my_mixed_tuple[3])
#new_tuple = my_mixed_tuple[:2] + ("E=mc^2", ">>ψψ<<") + my_mixed_tuple[2:]

#print(new_tuple)

# Exercise 5
book_info = {
    "title": "The Great Book",
    "author": "Jane Doe",
    "year": 1990,
    "genre": "Fiction",
    "characters": ["Alice", "Bob", "Charlie"]
}
#author = "Jane Doe"
#new_character = "william_the_bonk"
#characters = "Alice", "Bob", "Charlie"
title = "The Great Book"
genre =  "Fiction"
#new_characters = (new_character,) + characters
#print(new_characters)

import datetime

data = {"year": 1990}

current_year = datetime.datetime.now().year

data["year"] = current_year

#print(data)

# Exercise 6

# Conditional Logic with Collections
my_list = ['item1', 'item2', 'item3']
# Write the conditional logic based on list length